### ISSUE TITLE
Android real device: Using require("img") on src makes image 4 tiems bigger

### ISSUE THREAD

**Issue by rendomnet** [JimmyDaddy/react-native-image-marker#29]
**Describe the bug**
This bug occurs on my android device Android 7.0 LG V20
When using markImage and markText it gives me incorrect results

**To Reproduce**
When I use markText or markImage with require("...") it acts as src image is 4 times bigger.
and as result marker image or text becomes 4 times smaller.
```
let img = await ImageMarker.markText({
        src: require("../img.png"),
        markerSrc: {uri: ..},
        X: 0,
        Y: 0,
        scale: 1,
        markerScale: 1,
        quality: 20
      });
```
So if I merge two images of the same size 100px x 100px then marker image will be just 25px x 25px square on top of 100px x 100px src.

**Expected behavior**
Correct merging

**Screenshots**
![image](https://user-images.githubusercontent.com/18900210/52619063-e8789980-2eca-11e9-8307-c418b5d0eeab.png)

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs:  [e.g. 8.9.0]
 - react-native: 0.57.8
 - react-native-image-marker :  0.43

**Smartphone (please complete the following information):**
 - Device: LG v20
 - OS: Android 7.0

**Comment by rendomnet** [comment]
bug is disappeared.... I will recreate if it will up again.

**Comment by rendomnet** [comment]
Okay this issue occurs only on release

**Comment by JimmyDaddy** [comment]
@rendomnet Did this bug occurs on simulators?

**Comment by rendomnet** [comment]
@JimmyDaddy no. On simulator no issue.

**Comment by rendomnet** [comment]
@JimmyDaddy so i hack/fixed it by doing. 
```
    let mergedImg1 = await ImageMarker.markImage({
        src: require("img1.png"),
        markerSrc: require("img1.png"),
        X: 0,
        Y: 0,
        scale: 1,
        markerScale: 1,
        quality: 20
      });
```
and then putting marker text and images on **mergedImg1** then it uses correct size.
But if put marker on require('img1') then it is unstable if it will use correct image size.

**Comment by JimmyDaddy** [comment]
@rendomnet  I'll test and fix this when I get a test device.

**Comment by rendomnet** [comment]
Still have this issue. 0.5.1.
It happens only on real device.
Something wrong with scaling on android

**Comment by JimmyDaddy** [comment]
fixed on [v0.6.0](https://www.npmjs.com/package/react-native-image-marker), but you need to upgrade your RN to v0.60.0+ because of [fresco version](https://github.com/facebook/react-native/blob/8cf9505bd27c5dade33b17cc177fa5ef1613dbcd/ReactAndroid/gradle.properties#L15)

**Comment by michael-harley** [comment]
This still happens, I'm using 

**react-native**: "0.61.4"
**react-native-image-marker**: "^0.6.1"

on **Android 8**

I tried using `import img from 'src'` and `require('src')`, both result in the image getting bigger 4x.

**Comment by anija** [comment]
Same issue here, version 0.6.1

**Comment by PaperMonster** [comment]
I'm facing the same issue with 0.6.1 but in my case, the marker image is 3 times larger than expected. It only happens in release build and when using `require('...')` as marker source. My current workaround is using remote image via `{uri: ...}` instead.

**Comment by virenradadiya** [comment]
Hi there,
I am also facing the same issue. Has anyone found a solution yet? It would be really helpful if someone could share a workaround or any insights on how to resolve this problem. 

Thank you!
