### ISSUE TITLE
On some Android devices marker image sometimes scales a lot, code the same - result is different

### ISSUE THREAD

**Issue by Yaniislav** [JimmyDaddy/react-native-image-marker#49]
**Describe the bug**
On such devices as Xiaomi Redmi 5+ (Android 8.1) or Samsung Galaxy J7 Prime (Android 7.0) scale of marker image seems to be increased a lot. It happens not always, but it's really weird. We use the same code on different devices with the same picture and get different size of marker image as result.

**To Reproduce**
 We use this code to calculate scale value for marker. Pay attention that **width** and **height** - are image sizes. **imageHeight** and **imageWidth** - are marker image sizes. We use this code to make marker size as half size of image we put it on.
 ``` let smmallerImageSide = width;
  let smallerWatermarkSide = imageWidth;

  if (height < width) {
    smmallerImageSide = height;
    smallerWatermarkSide = imageHeight;
  }

  const scale = (smmallerImageSide / 2) / smallerWatermarkSide;

 if (isAndroid) {
    const pathAfterMarkedText = await ImageMarker.markImage({
      src: { uri: 'data:img/jpg;base64,${data}'},
      markerSrc: Watermark, // icon uri
      position: 'center',
      scale: 1, // scale of bg
      markerScale: scale, // scale of icon
      quality: 100
    });
```

**Expected behavior**
Result size of marker image should be the same on all devices with the same picture

**Devlopment environment(please complete the following information):**
 - OS: Mac OS
 - react-native: 0.59.9
 - react-native-image-marker :  0.4.4

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 5+, Samsung Galaxy J7 Prime 
 - OS: Android 8.1, Android 7

**Comment by JimmyDaddy** [comment]
That may relative to Device Resolution or Pixel Density, I'll figure it out when I am available

**Comment by summer88123** [comment]
The library use Fresco to decode image, and Fresco may change image size!
In our case, we use Fresco-1.11.0. There is a config `ImagePipelineConfig.Builder.experiment().setMaxBitmapSize()`, default value is 2048. If your image width or height bigger then maxBitmapSize, Fresco will calculate a SampleSize before decode. @Yaniislav @JimmyDaddy

**Comment by Yaniislav** [comment]
> The library use Fresco to decode image, and Fresco may change image size!
> In our case, we use Fresco-1.11.0. There is a config `ImagePipelineConfig.Builder.experiment().setMaxBitmapSize()`, default value is 2048. If your image width or height bigger then maxBitmapSize, Fresco will calculate a SampleSize before decode. @Yaniislav @JimmyDaddy
@JimmyDaddy , We restrict image sizes on js side, so the image passed to native side has width and height less than 2048. Please, help us to fix it, because we are on release stage and this is the only thing that remain unfixed. Thanks!

**Comment by JimmyDaddy** [comment]
fixed on [v0.6.0](https://www.npmjs.com/package/react-native-image-marker), but you need to upgrade your RN to v0.60.0+ because of [fresco version](https://github.com/facebook/react-native/blob/8cf9505bd27c5dade33b17cc177fa5ef1613dbcd/ReactAndroid/gradle.properties#L15)

And thank you  @summer88123

**Comment by kukuandroid** [comment]
Hi, im still facing this issue . 
RN: 0.61.5
libray : latest version.
Anyone solved this issue ?
